# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField(unique=True)),
                ('userID', models.IntegerField(unique=True)),
                ('source', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('numLinks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=128, unique=True)),
                ('userID', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=128)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
