# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170308_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'userprofiles'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userName',
            new_name='username',
        ),
    ]
