# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170308_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='username',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
