# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_game_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gameID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='game',
            name='bestLinks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='numLinks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
