# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_userprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
